
name: Update Data

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Update Data
      env:
        TANDOOR_API_KEY: ${{ secrets.TANDOOR_API_KEY }}
      run: |
        python update_data.py
    - name: Validate data
      run: |
        python validate.py
    - name: Update Translations
      run: |
        python build_translations.py
    - name: Update Data
      run: |
        python build.py
    - uses: stefanzweifel/git-auto-commit-action@v4
